### ISSUE TITLE
Smartblog creates dublicate meta tags

### ISSUE THREAD

**Issue by chacco76** [smartdatasoft/smartblog#99] opened 2018-06-29 17:04 UTC
After an SEO analysis I realized that every page ( even the not blog related ones ) contain meta title, tags and description twice. Tried to figure out how it is happening, but I'm not deep enough into prestashop. Probably a hook problem?

**Comment by chacco76** [comment] 2018-07-20 17:17
@smartdatasoft

**Comment by Tatagalax** [comment] 2018-11-12 16:39
Thanks for asking Chacco, I'd be interested by an answer too, i'm encountering the exact same problem. The module is duplicating the meta title and description set for the blog page to EVERY page on the website


<link rel="alternate" type="application/rss+xml" title="This is supposed to be my blog page meta title but it appears on every page" href="http://mywebsite.fr/modules/smartblog/rss.php" />
  |  
  | <meta name="title" content="This is supposed to be my blog page title but it appears on every page">
  | <meta name="keywords" content="This is supposed to be my blog page keywords but it appears on every page">
  | <meta name="description" content="This is supposed to be my blog page meta description but it appears on every page">
  |  
  | </head>


TEST 1 :
I tried turning blog module off, and the problem disappeared ; so it seems like the problem is coming (indeed) from SmartBlog module.

TEST 2 : 
I also tried, keeping the blog plugin on, turning off every other complementary modules, to see if the problem was coming from another plugin from SmartDataSoft (as smartblog is linked with a dozen plugins) ; but while every other plugin off and only smartblog

TEST 3 : 
I tried (with smarblog and every other linked plugin on), to just NOT fill meta title, meta keywords and meta description labels. I was hoping the <meta> would disappear ; but they remain, empty though.


<link rel="alternate" type="application/rss+xml" title="" href="http://mywebsite.fr/modules/smartblog/rss.php" />
--
  |  
  | <meta name="title" content="">
  | <meta name="keywords" content="">
  | <meta name="description" content="">
  |  
  | </head>


If anyone has a solution, a patch or even an idea i'd be happy to get some help.

@chacco76 if you read me, your post was in July, did you find a solution ?

Thanks a lot

**Comment by chacco76** [comment] 2018-11-12 18:47
I didn´t really find a good solution, as our blog isn´t too important right now. I just commented the lines in the blog article file out, the blog articles will have a standard title and no meta description then. 


Cheers

Oliver

 

Von: Tatagalax <notifications@github.com> 
Gesendet: Montag, 12. November 2018 17:40
An: smartdatasoft/smartblog <smartblog@noreply.github.com>
Cc: chacco76 <oliver@fraenky.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [smartdatasoft/smartblog] Smartblog creates dublicate meta tags (#99)

 

Thanks for asking Chacco, I'd be interested by an answer too, i'm encountering the exact same problem. The module is duplicating the meta title and description set for the blog page to EVERY page on the website

`

  |     |   |   |   |     | 

`

TEST 1 :
I tried turning blog module off, and the problem disappeared ; so it seems like the problem is coming (indeed) from SmartBlog module.

TEST 2 :
I also tried, keeping the blog plugin on, turning off every other complementary modules, to see if the problem was coming from another plugin from SmartDataSoft (as smartblog is linked with a dozen plugins) ; but while every other plugin off and only smartblog

TEST 3 :
I tried (with smarblog and every other linked plugin on), to just NOT fill meta title, meta keywords and meta description labels. I was hoping the would disappear ; but they remain, empty though.

`

--   |     |     |   |   |   |     |     |     |     |     | 

`

If anyone has a solution, a patch or even an idea i'd be happy to get some help.

@chacco76 <https://github.com/chacco76>  if you read me, your post was in July, did you find a solution ?

Thanks a lot

**Comment by smartdatasoft** [comment] 2018-11-13 04:00
@ chacco76   which release version you have tested. What i know the meta tag is removed from our current git version. Will you please check from our release zip

**Comment by Tatagalax** [comment] 2018-11-21 13:48
Hi, 

Thanks @chacco76 for the answer

And @smartdatasoft i have the same problem and i'm using the Version 3.0.0 wich seems to be the last one. By the way, I'm using Prestashop 1.7.4.2

Thanks a lot

**Comment by wordliner** [comment] 2018-12-01 11:12
I have default meta data instead of proper smart blod titles. I am on 1.7.4.3

**Comment by catbirdbingo** [comment] 2019-03-03 11:03
I have exact same problem. 

I found this code in smartblog.php

     if($id_post){
            $obj_post = new SmartBlogPost($id_post, true, $this->context->language->id, $this->context->shop->id);
            $meta_title = $obj_post->meta_title;
            $meta_keyword = $obj_post->meta_keyword;
            $meta_description = $obj_post->meta_description;
        } else {
            $meta_title = 'SmartBlog Category';
            $meta_keyword = 'smartblog, smartblogcategory';
            $meta_description = 'Access SmartBlog Category';
        }

Looking at the code, it seems that the tags should be substituted only on the page with the post, but these tags are on the main page and on the category and product page..

PS 1.6.1.23
Smartblog 2.2.0 from github

Any solution ? @smartdatasoft
Thanks.

**Comment by catbirdbingo** [comment] 2019-03-03 15:58
Guys @Tatagalax, @chacco76, you got any solution?

**Comment by catbirdbingo** [comment] 2019-03-03 16:06
Also, there is duplicate tags on the blog post page!!

**Comment by urbanita** [comment] 2019-04-12 08:53
Hi! I managed to solve this.
In the "smartblog.php", add a simple if statement to the hookDisplayHeader function, like this:
`    public function hookDisplayHeader($params)
    {
        if (strstr($_SERVER['REQUEST_URI'], 'smartblog')) {
            /*function content*/
        }
    }`
So, the function that mess up the meta tags, only works in smartblog pages

**Comment by catbirdbingo** [comment] 2019-04-12 18:47
> Hi! I managed to solve this.
> In the "smartblog.php", add a simple if statement to the hookDisplayHeader function, like this:
> ` public function hookDisplayHeader($params) { if (strstr($_SERVER['REQUEST_URI'], 'smartblog')) { /*function content*/ } }`
> So, the function that mess up the meta tags, only works in smartblog pages

Thanks bro, your solution works perfect!

**Comment by sirius82** [comment] 2019-08-13 23:20
hi ! I tried it on smartblog 3.0.0 and PS 1.7.5.2 but it seems it doesn't work correctly :
before, I had 2 meta title and 2 meta description. First of each was empty, the second contained the title and the description tags of posts. 
After, I have only the empty meta tags. But meta property og:description and og:title are correctly filled.
I filled in each field "meta description" in posts. But not in the module configuration
Do you have an idea ?

Thanks a lot !

**Comment by sirius82** [comment] 2019-08-15 22:33
Hello, I think it's  the pugin blogfeedheader.tpl (in modules/smartblog/views/template/front/plugins) and these meta are for RSS. The only way I found to not display these meta on other pages than blog is to add exceptions for all pages of core (in Positions -> select Smart Blog in the position Header -> Modify -> in Exceptions select all pages). So, I've duplicate meta only on blog pages. It's a little beter. But there are always the first meta wich are empty. How is it possible to have only one of each and filled with title and description of post ???
Thanks

**Comment by tmsio** [comment] 2019-10-21 21:33
Hello, Any news about this problem?
Regards

**Comment by tmsio** [comment] 2019-10-22 08:55
Hello i found this solution, and in my environment (prestashop 1.7.6.1 smartblog 3.0.0)work fine:
in my head.tpl file:
/htdocs/themes/your_theme/templates/_partials

modify seo block in:

{block name='head_seo'}

  {if $page.meta.keywords}
  <title>{block name='head_seo_title'}{$page.meta.title}{/block}</title>
  <meta name="description" content="{block name='head_seo_description'}{$page.meta.description}{/block}">
  <meta name="keywords" content="{block name='head_seo_keywords'}{$page.meta.keywords}{/block}">
  
  {elseif $meta_description }
  
  <link rel="alternate" type="application/rss+xml" title="{$meta_title|escape:html:'UTF-8'}" href="{$feedUrl}" />
  <title>{$meta_title}</title>
  <meta name="title" content="{$meta_title}">
  <meta name="keywords" content="{$meta_keyword}">
  <meta name="description" content="{$meta_description}">
  
  {elseif $post.meta_title }
  <link rel="alternate" type="application/rss+xml" title="{$meta_title|escape:html:'UTF-8'}" href="{$feedUrl}" />
  <title>{$post.meta_title}</title>
  <meta name="title" content="{$post.meta_title}">
  <meta name="keywords" content="{$post.meta_keyword}">
  <meta name="description" content="{$post.meta_description}">
  {/if}
  
  
  {if $page.meta.robots !== 'index'}
    <meta name="robots" content="{$page.meta.robots}">
  {/if}
  {if $page.canonical}
    <link rel="canonical" href="{$page.canonical}">
  {/if}
{/block}



Regards.

Emiliano

**Comment by Enumbin** [comment] 2021-02-02 10:10
The issue is fixed on version 4.0.0 For further support open support ticket on https://support.classydevs.com/support/

**Closed as completed by Enumbin** 2021-02-02 10:10 UTC
