### ISSUE TITLE
smartblog not possible to deinstall on whole, nor components you don't want to use

### ISSUE THREAD

**Issue by cd2500** [smartdatasoft/smartblog#98] opened 2018-06-29 08:59 UTC
It is not possible to deinstall sole widget modules like "smartblog addthis button", or other. Nor it is possible to deinstall the complete smartblog with his widgets.
There is no error. It simply does nothing, although when I click only one widget for to be deinstalled it firstly shows that it is deinstalled, but when I return to modules -> modules site it is again installed.
Pleas make it possible to deinstall some components (comments you cannot deinstall as well, if you don't want to use them).
PS 1.6.1.18, php version 5.6.30
Smart Blog 2.2.0,
Smart Blog Search 2.0.1
Smart Blog Archiv 2.0.4
Smart Blog Feed 2
Smart Blog Home Latest News 2.0
Smart Blog Latest Comments 2.0.1
Smart Blog AddThisButton 2.0.3
Smart Blog Popular Posts 2.0.1
Smart Blog Recent Posts 2.0.1
Smart Blog Tag 2.0.1

**Comment by Enumbin** [comment] 2021-02-02 10:22
The issue is fixed on version 4.0.0

For further issue open support ticket on https://support.classydevs.com/support/

**Closed as completed by Enumbin** 2021-02-02 10:22 UTC
